apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: node-deployment
spec:
  # 3 Pods should exist at all times.
  replicas: 4
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: react-app
    spec:
      containers:
      - name: node-container1
        # Run this image
        image: kadiransari7208/node-express:01
